name: Terraform EKS Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "yes" to confirm deployment'
        required: true
        default: 'no'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.inputs.confirmation == 'yes' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120

    env:
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::142969859154:role/eks-threat-composer-github-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: TFLint Check
        working-directory: terraform
        run: |
          tflint --init
          tflint

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply --auto-approve
